/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application_Compta;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import static org.bouncycastle.asn1.x500.style.RFC4519Style.st;
import requetepoolthreads.Reponse;
import utilitaire.BaseException;
import utilitaire.FichierConfig;

/**
 *
 * @author Nicolas
 */
public class Applic_Data_Analysis extends javax.swing.JFrame {

    public static Socket cliSock;
    public static FichierConfig ConfigProperty = new FichierConfig();
    
    private String sepProperty;
    private String finChaine;
    
    private static PrivateKey pkClient;
    private static PublicKey pkServer;
    private static SecretKey keySession;
    private static SecretKey keyHmac;
    
    private java.awt.Frame parent;
    /**
     * Creates new form Applic_Data_Analysis
     * @param sock
     * @param privateKeyClient
     * @param publicKeyServer
     * @param cleSession
     * @param cleHmac
     */
    
    public Applic_Data_Analysis(Socket sock, PrivateKey privateKeyClient, PublicKey publicKeyServer, SecretKey cleSession, SecretKey cleHmac) {
        initComponents();
        cliSock = sock;
        sepProperty = ConfigProperty.getConfig().getProperty("separateur");
        finChaine = ConfigProperty.getConfig().getProperty("finChaine");  
        
        pkClient = privateKeyClient;
        pkServer = publicKeyServer;
        keySession = cleSession;
        keyHmac = cleHmac;
    }
    
    public void NextBill() throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IOException, IllegalBlockSizeException, BadPaddingException, BaseException
    {
        DataInputStream dis= new DataInputStream(cliSock.getInputStream());
        String message = "GET_NEXT_BILL" + finChaine;
        
        Envoyer(message);
        
        String reponse = dis.readUTF(); 
        
        if (reponse.equals("oui"))
        {
            int size = dis.readInt();
            byte[] factureCryptée = new byte[size];
            dis.readFully(factureCryptée);
            
            Cipher chiffrementd = Cipher.getInstance("DES/ECB/PKCS5Padding");
            chiffrementd.init(Cipher.DECRYPT_MODE, keySession);
            byte[] texteDécodé = chiffrementd.doFinal(factureCryptée);
            String texteDécodéClair = new String (texteDécodé);
            System.out.println(new String(factureCryptée) + " ---> " + texteDécodéClair);
        }
        else
        {
            throw new BaseException(this.parent, "pas de facture disponible");
        }
    }
    
    public String Envoyer(String message)
    {
        String reponse = null;
        try 
        {
            DataOutputStream dos= new DataOutputStream(cliSock.getOutputStream());

            dos.writeUTF(message);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return reponse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        RBNextBill = new javax.swing.JRadioButton();
        jTextField_Reponse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_Envoyer = new javax.swing.JButton();
        RBTestHyp = new javax.swing.JRadioButton();
        TFNbContainers1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LPvalue = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RBTestHom = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        TFNbContainers2 = new javax.swing.JTextField();
        RBAnova = new javax.swing.JRadioButton();
        TFNbContTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RBNextBill.setText("dernière facture");
        RBNextBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNextBillActionPerformed(evt);
            }
        });

        jTextField_Reponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ReponseActionPerformed(evt);
            }
        });

        jLabel9.setText("Réponse :");

        jButton_Envoyer.setText("DEMANDE");
        jButton_Envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnvoyerActionPerformed(evt);
            }
        });

        buttonGroup3.add(RBTestHyp);
        RBTestHyp.setText("Test_Hypothèse_Conf");
        RBTestHyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTestHypActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre de containers 1 :");

        LPvalue.setText("??");

        jLabel14.setText("pvalue :");

        buttonGroup3.add(RBTestHom);
        RBTestHom.setText("Test_Hypothèse_Hom");
        RBTestHom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTestHomActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre de containers 2:");

        RBAnova.setText("Anova");

        jLabel15.setText("Nombre total containers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(RBNextBill)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(RBTestHyp)
                                .addGap(60, 60, 60)
                                .addComponent(RBTestHom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBAnova))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel14)
                                .addGap(26, 26, 26)
                                .addComponent(LPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(TFNbContainers1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(TFNbContainers2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(40, 40, 40)
                                .addComponent(TFNbContTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel9)
                        .addGap(167, 167, 167)
                        .addComponent(jTextField_Reponse, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(jButton_Envoyer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBNextBill)
                    .addComponent(RBTestHyp)
                    .addComponent(RBTestHom)
                    .addComponent(RBAnova))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNbContainers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(TFNbContainers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNbContTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jButton_Envoyer)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Reponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ReponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ReponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ReponseActionPerformed

    private void jButton_EnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnvoyerActionPerformed
       
        String message = null;
        
        if(RBNextBill.isSelected())
            try {
                NextBill();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadPaddingException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BaseException ex) {
            Logger.getLogger(Applic_Data_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_EnvoyerActionPerformed

    private void RBTestHomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTestHomActionPerformed
        TFNbContainers2.setEnabled(true);
    }//GEN-LAST:event_RBTestHomActionPerformed

    private void RBNextBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNextBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBNextBillActionPerformed

    private void RBTestHypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTestHypActionPerformed
        TFNbContainers2.setEnabled(false);
    }//GEN-LAST:event_RBTestHypActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applic_Data_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applic_Data_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applic_Data_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applic_Data_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applic_Data_Analysis(cliSock,pkClient,pkServer,keySession,keyHmac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LPvalue;
    private javax.swing.JRadioButton RBAnova;
    private javax.swing.JRadioButton RBNextBill;
    private javax.swing.JRadioButton RBTestHom;
    private javax.swing.JRadioButton RBTestHyp;
    private javax.swing.JTextField TFNbContTotal;
    private javax.swing.JTextField TFNbContainers1;
    private javax.swing.JTextField TFNbContainers2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton_Envoyer;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField_Reponse;
    // End of variables declaration//GEN-END:variables
}
