/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application_Compta;

import Classes.Facture;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import static org.bouncycastle.asn1.x500.style.RFC4519Style.st;
import requetepoolthreads.Reponse;
import utilitaire.BaseException;
import utilitaire.FichierConfig;

/**
 *
 * @author Nicolas
 */
public class Applic_Compta extends javax.swing.JFrame {

    public static Socket cliSock;
    public static FichierConfig ConfigProperty = new FichierConfig();
    
    private String sepProperty;
    private String finChaine;
    
    private static PrivateKey pkClient;
    private static PublicKey pkServer;
    private static SecretKey keySession;
    private static SecretKey keyHmac;
    
    private static final int coord_x = 450;
    private static final int coord_y = 200;
    
    
    
    private java.awt.Frame parent;
    /**
     * Creates new form Applic_Data_Analysis
     * @param sock
     * @param privateKeyClient
     * @param publicKeyServer
     * @param cleSession
     * @param cleHmac
     */
    
    public Applic_Compta(Socket sock, PrivateKey privateKeyClient, PublicKey publicKeyServer, SecretKey cleSession, SecretKey cleHmac) {
        initComponents();
        setLocation(coord_x, coord_y);
        cliSock = sock;
        sepProperty = ConfigProperty.getConfig().getProperty("separateur");
        finChaine = ConfigProperty.getConfig().getProperty("finChaine");  
        
        pkClient = privateKeyClient;
        pkServer = publicKeyServer;
        keySession = cleSession;
        keyHmac = cleHmac;
    }
    
    public void NextBill() throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IOException, IllegalBlockSizeException, BadPaddingException, BaseException
    {
        DataInputStream dis= new DataInputStream(cliSock.getInputStream());
        String message = "GET_NEXT_BILL" + finChaine;
        
        Envoyer(message);
        
        String reponse = dis.readUTF(); 
        
        if (reponse.equals("oui"))
        {
            int size = dis.readInt();
            byte[] factureCryptée = new byte[size];
            dis.readFully(factureCryptée);
            
            Cipher chiffrementd = Cipher.getInstance("DES/ECB/PKCS5Padding");
            chiffrementd.init(Cipher.DECRYPT_MODE, keySession);
            byte[] texteDécodé = chiffrementd.doFinal(factureCryptée);
            String texteDécodéClair = new String (texteDécodé);
            System.out.println(new String(factureCryptée) + " ---> " + texteDécodéClair);
            
            Facture facture  = new Facture(texteDécodéClair);
            
            FenFactureValidation fenFactVal = new FenFactureValidation(parent, true, facture, cliSock,pkClient);
            fenFactVal.setVisible(true);
        }
        else
        {
            throw new BaseException(this.parent, "pas de facture disponible");
        }
    }
    
    public String Envoyer(String message)
    {
        String reponse = null;
        try 
        {
            DataOutputStream dos= new DataOutputStream(cliSock.getOutputStream());

            dos.writeUTF(message);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return reponse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField_Reponse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BNextBill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BSendBills = new javax.swing.JButton();
        BListBills = new javax.swing.JButton();
        jButton_Paiement = new javax.swing.JButton();
        jButton_FNP = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Reponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ReponseActionPerformed(evt);
            }
        });

        jLabel9.setText("Réponse :");

        BNextBill.setText("derniere facture");
        BNextBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNextBillActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Application comptable");

        BSendBills.setText("factures validées");
        BSendBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSendBillsActionPerformed(evt);
            }
        });

        BListBills.setText("Liste des factures d'une société");
        BListBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BListBillsActionPerformed(evt);
            }
        });

        jButton_Paiement.setText("Paiement");
        jButton_Paiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PaiementActionPerformed(evt);
            }
        });

        jButton_FNP.setText("factures non payées");
        jButton_FNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FNPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BSendBills)
                    .addComponent(jLabel1)
                    .addComponent(jButton_FNP))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField_Reponse, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(BListBills, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Paiement)
                            .addComponent(BNextBill))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNextBill)
                    .addComponent(BSendBills))
                .addGap(42, 42, 42)
                .addComponent(BListBills)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Paiement)
                    .addComponent(jButton_FNP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Reponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ReponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ReponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ReponseActionPerformed

    private void BNextBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNextBillActionPerformed
       
        try {
                NextBill();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadPaddingException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BaseException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BNextBillActionPerformed

    private void BSendBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSendBillsActionPerformed
        FenListeFactures fenFactVal;
        try {
            fenFactVal = new FenListeFactures(parent, true, cliSock,pkClient);
            fenFactVal.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BSendBillsActionPerformed

    private void BListBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BListBillsActionPerformed
        FenListBill fenListeSoc;
        try {
            fenListeSoc = new FenListBill(parent, true, cliSock,pkClient,keySession);
            fenListeSoc.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Applic_Compta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BListBillsActionPerformed

    private void jButton_PaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PaiementActionPerformed
        Fen_Paiement fen = new Fen_Paiement (this, true, cliSock, pkClient, pkServer, keySession, keyHmac);
        fen.setVisible(true);
    }//GEN-LAST:event_jButton_PaiementActionPerformed

    private void jButton_FNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FNPActionPerformed
        Fen_ListWaiting fen = new Fen_ListWaiting (this, true, cliSock);
        fen.setVisible(true);
    }//GEN-LAST:event_jButton_FNPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applic_Compta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applic_Compta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applic_Compta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applic_Compta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applic_Compta(cliSock,pkClient,pkServer,keySession,keyHmac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BListBills;
    private javax.swing.JButton BNextBill;
    private javax.swing.JButton BSendBills;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_FNP;
    private javax.swing.JButton jButton_Paiement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField_Reponse;
    // End of variables declaration//GEN-END:variables
}
