/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application_Compta;

import static Application_Compta.Applic_Compta.ConfigProperty;
import static Application_Compta.Fen_Paiement.cliSock;
import Classes.Facture;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class Fen_ListWaiting extends javax.swing.JDialog {

    /**
     * Creates new form Fen_ListWaiting
     */
    public static Socket cliSock;
    
    private String sepProperty;
    private String finChaine;
    
    private Object[] col = { "ID", "SociÃ©tÃ©", "Date", "Montant total", "Montant Ã  payer", "Moyen envoi" };
    private DefaultTableModel Model_Factures= new DefaultTableModel(col, 0);
    
    public Fen_ListWaiting(java.awt.Frame parent, boolean modal, Socket sock) {
        super(parent, modal);
        initComponents();
        
        cliSock = sock;
        sepProperty = ConfigProperty.getConfig().getProperty("separateur");
        finChaine = ConfigProperty.getConfig().getProperty("finChaine");  
        
        
        jRadioButton_Toutes.setSelected(true);
        
        jTable_Factures.setModel(Model_Factures); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Fermer = new javax.swing.JButton();
        jButton_OK = new javax.swing.JButton();
        jRadioButton_Toutes = new javax.swing.JRadioButton();
        jRadioButton_Soc = new javax.swing.JRadioButton();
        jRadioButton_Mois = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Soc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Factures = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_Fermer.setText("Fermer");

        jButton_OK.setText("Ok");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jRadioButton_Toutes.setText("TOUTES");

        jRadioButton_Soc.setText("Par société");

        jRadioButton_Mois.setText("De plus d'un mois");

        jLabel1.setText("Nom société :");

        jTable_Factures.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable_Factures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Societe", "Date", "Montant Total", "Montant Restant", "Moyen d'envoi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Factures.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Factures);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Affichage des factures");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jRadioButton_Toutes)
                .addGap(149, 149, 149)
                .addComponent(jRadioButton_Soc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_Mois)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jButton_OK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Soc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton_Fermer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Toutes)
                    .addComponent(jRadioButton_Soc)
                    .addComponent(jRadioButton_Mois))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Soc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton_OK)
                .addGap(32, 32, 32)
                .addComponent(jButton_Fermer)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        String message = "";
        
        Model_Factures.setRowCount(0);
        
        FileInputStream fis = null;
        DataOutputStream dos = null;
        DataInputStream dis = null;
        ObjectInputStream ois = null;
        
        try 
        {
            System.out.println(cliSock.getInetAddress().toString()); 
            dos = new DataOutputStream(cliSock.getOutputStream());
            
        } catch (UnknownHostException e) { System.err.println("Erreur ! Host non trouvÃ© [" + e + "]"); 
        } catch (IOException e) { System.err.println("Erreur ! Pas de connexion ? [" + e + "]");}
        
        try
        {
            if (jRadioButton_Toutes.isSelected())
            {
                message = "LIST_WAITING" + sepProperty + "TOUTES" + finChaine;
                dos.writeUTF(message);  
            }

            if (jRadioButton_Soc.isSelected())
            {
                message = "LIST_WAITING" + sepProperty + "SOC" + sepProperty + jTextField_Soc.getText() + finChaine;
                dos.writeUTF(message); 
            }

            if (jRadioButton_Mois.isSelected())
            {
                message = "LIST_WAITING" + sepProperty + "MOIS" + finChaine;
                dos.writeUTF(message); 
            }
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Fen_ListWaiting.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try 
        {
            Facture f;
            
            fis = new FileInputStream("data.txt");
            ois = new ObjectInputStream(fis);
            dis = new DataInputStream(new BufferedInputStream(cliSock.getInputStream()));
            
            int taille = dis.readInt();
            
            
            for (int i=0; i < taille; i++)
            {
                f = (Facture)ois.readObject();
                Model_Factures.insertRow(i, new Object[]{f.getIdFacture(), f.getSociete(), f.getDate(), f.getMontantTotal(), f.getMontantAPayer(), f.getMoyenEnvoi()});
            }
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Fen_ListWaiting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fen_ListWaiting.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fen_ListWaiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fen_ListWaiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fen_ListWaiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fen_ListWaiting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fen_ListWaiting dialog = new Fen_ListWaiting(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fermer;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton_Mois;
    private javax.swing.JRadioButton jRadioButton_Soc;
    private javax.swing.JRadioButton jRadioButton_Toutes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Factures;
    private javax.swing.JTextField jTextField_Soc;
    // End of variables declaration//GEN-END:variables
}
